# Generated by Django 2.0 on 2018-12-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181224_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslisting',
            name='service_type',
            field=models.CharField(default=250, max_length=250),
        ),
    ]
