# Generated by Django 2.0.6 on 2019-01-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceslisting_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceslisting',
            name='service_type',
        ),
    ]
