# Generated by Django 2.0 on 2019-01-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_serviceslisting_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslisting',
            name='order_uuid',
            field=models.CharField(default='', max_length=250),
        ),
    ]
