# Generated by Django 2.0 on 2019-01-02 23:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceslisting_order_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceslisting',
            old_name='service_name',
            new_name='topi',
        ),
        migrations.RemoveField(
            model_name='serviceslisting',
            name='price',
        ),
        migrations.AddField(
            model_name='serviceslisting',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
