# Generated by Django 2.0 on 2019-01-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190102_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceslisting',
            old_name='topi',
            new_name='topic',
        ),
    ]
