# Generated by Django 2.0 on 2018-08-01 23:52

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('land_photo', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('area_located', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=250)),
                ('contact_email', models.EmailField(max_length=254)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('posted_by', models.CharField(choices=[('property owner', 'property owner'), ('agent', 'agent'), ('tenant', 'tenant')], max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('videolink', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), size=None)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=250)),
                ('listings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('property_type', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial')], max_length=250)),
                ('property_listing_type', models.CharField(choices=[('condo', 'condo'), ('apartment', 'apartment'), ('home', 'home')], max_length=250)),
                ('prop_stats', models.BooleanField(default=False)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('square_feet', models.FloatField(default=137.26)),
                ('contact_email', models.EmailField(max_length=254)),
                ('posted_by', models.CharField(choices=[('property owner', 'property owner'), ('agent', 'agent'), ('tenant', 'tenant')], max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('image', models.ImageField(upload_to='')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
