# Generated by Django 2.0 on 2018-08-01 23:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None),
        ),
    ]
