# Generated by Django 2.0 on 2018-08-04 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20180801_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='image',
        ),
        migrations.AddField(
            model_name='landlisting',
            name='phone_five',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='phone_four',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='phone_three',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='phone_two',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='photo_one',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='phone_five',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='phone_four',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='phone_three',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='phone_two',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='photo_one',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='videolink',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
