# Generated by Django 2.0 on 2018-08-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20180804_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlisting',
            old_name='area_located',
            new_name='address',
        ),
        migrations.AddField(
            model_name='landlisting',
            name='city',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='state',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='state',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
