# Generated by Django 2.0 on 2018-08-05 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20180804_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='videolink',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, size=None),
        ),
    ]
