# Generated by Django 2.0.6 on 2018-12-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_auto_20181203_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='electricity',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='improvments',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='mortgages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='owner_association',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='sewer_source',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='square_feet',
            field=models.FloatField(default=137.26),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='taxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='water_source',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
