# Generated by Django 2.0 on 2018-12-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20181203_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='contact_profile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='contact_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='contact_profile_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
