# Generated by Django 2.0 on 2018-12-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_auto_20181205_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlisting',
            old_name='phone_five',
            new_name='photo_five',
        ),
        migrations.RenameField(
            model_name='landlisting',
            old_name='phone_four',
            new_name='photo_four',
        ),
        migrations.RenameField(
            model_name='landlisting',
            old_name='phone_three',
            new_name='photo_three',
        ),
        migrations.RenameField(
            model_name='landlisting',
            old_name='phone_two',
            new_name='photo_two',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='phone_five',
            new_name='photo_five',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='phone_four',
            new_name='photo_four',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='phone_three',
            new_name='photo_three',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='phone_two',
            new_name='photo_two',
        ),
    ]
