# Generated by Django 2.0 on 2019-01-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_propertylisting_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlisting',
            old_name='price',
            new_name='amount',
        ),
    ]
