# Generated by Django 2.0.6 on 2018-12-30 19:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('room_quality', models.IntegerField(default=0)),
                ('facilites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('website', models.URLField(blank=True)),
                ('order_uuid', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pub_dat', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('phone_number2', models.CharField(blank=True, max_length=200, null=True)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
