# Generated by Django 2.0.6 on 2018-12-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20181230_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellisting',
            name='order_uuid',
            field=models.CharField(max_length=250),
        ),
    ]
