# Generated by Django 2.0 on 2019-02-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20190205_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
