# Generated by Django 2.0 on 2018-12-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='notify',
        ),
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
