# Generated by Django 2.0.6 on 2018-12-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_hotelinfo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='hotelinfo',
            name='work_identity',
        ),
    ]
