# Generated by Django 2.0.6 on 2018-12-29 15:56

import cloudinary.models
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181228_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='/avatar/customer.png', max_length=255, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='work_identity',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
