# Generated by Django 2.0.6 on 2018-12-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181229_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='order_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
