# Generated by Django 2.0.6 on 2018-12-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hotelinfo_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='location',
        ),
    ]
