# Generated by Django 2.0.6 on 2018-12-30 21:43

import cloudinary.models
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_hotelinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='hotel',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
