# Generated by Django 2.0.6 on 2019-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190101_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='service_type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='developerinfo',
            name='service_type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='governmentinfo',
            name='service_type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='supplier',
            name='service_type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='valuer',
            name='service_type',
            field=models.CharField(default='', max_length=250),
        ),
    ]
