# Generated by Django 2.0 on 2019-01-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190101_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='developerinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='governmentinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='servicesinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='location',
        ),
        migrations.RemoveField(
            model_name='valuer',
            name='location',
        ),
    ]
