# Generated by Django 2.0 on 2019-01-02 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190101_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='developerinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='governmentinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='servicesinfo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='servicesinfo',
            name='order_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='valuer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
