# Generated by Django 2.0 on 2019-02-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190208_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
